common:
db:
  mysql:
    addr: "root:aU0FEQ^#ad1@tcp(192.168.164.128:3306)/rook_db?charset=utf8mb4&parseTime=True&loc=Local"
  redis:
    addr: "192.168.164.128:6379"
    passwd: "123456"
    maxIdle: 8
    maxActive: 0
    idleTimeout: 100
server:
  midServer:
    logPath: ./mid.log
    debug: true
    port: 10000
  user:
    logPath: ./user.log
    debug: true
    port: 10000